# Generated by Django 4.1.7 on 2023-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.CharField(blank=True, default='https://thumbs.dreamstime.com/b/default-avatar-profile-icon-social-media-user-image-210115353.jpg', max_length=100000, null=True, verbose_name='Аватар'),
        ),
    ]
